name: Deployment of the Business application API

on:
  push:
    branches: ["ci-cd"]

jobs:
  deploy-business-application-api:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 5m
          script: |
            echo "Nice Job!!!"
